import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: 'Dashboard',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },

    {
        key: 'groupMenu.collapse',
        path: '',
        title: 'Global Settings',
        translateKey: 'nav.groupMenu.collapse.collapse',
        icon: 'globeCollapse',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'groupMenu.collapse.item11',
                path: '/state-manager',
                title: 'State',
                translateKey: 'nav.groupMenu.collapse.item11',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'groupMenu.collapse.collapse.remittanceTracker.collapse',
                path: '/remittance-tracker',
                title: 'Remittance Tracker',
                translateKey: 'nav.groupMenu.collapse.collapse.collapse',
                icon: '',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'groupMenu.collapse.collapse.collapse.remittanceTracker.collapse.remittanceTracker.item1',
                        path: '/pf-setup',
                        title: 'PF Setup',
                        translateKey: 'groupMenu.collapse.collapse.collapse.remittanceTracker.collapse.remittanceTracker.item1',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'groupMenu.collapse.collapse.collapse.remittanceTracker.collapse.remittanceTracker.item2',
                        path: '/esi-setup',
                        title: 'ESI Setup',
                        translateKey: 'groupMenu.collapse.collapse.collapse.remittanceTracker.collapse.remittanceTracker.item2',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },

                    {
                        key: 'groupMenu.collapse.collapse.collapse.remittanceTracker.collapse.remittanceTracker.item3',
                        path: '/lwf-setup',
                        title: 'LWF Setup',
                        translateKey: 'groupMenu.collapse.collapse.collapse.remittanceTracker.collapse.remittanceTracker.item3',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'groupMenu.collapse.collapse.collapse.remittanceTracker.collapse.remittanceTracker.item4',
                        path: '/pt-setup',
                        title: 'PT Setup',
                        translateKey: 'groupMenu.collapse.collapse.collapse.remittanceTracker.collapse.remittanceTracker.item4',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
            // {
            //     key: 'groupMenu.collapse.item2',
            //     path: '/district',
            //     title: 'District',
            //     translateKey: 'nav.groupMenu.collapse.item2',
            //     icon: '',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     authority: [],
            //     subMenu: [],
            // },
            // {
            //     key: 'groupMenu.collapse.item3',
            //     path: '/compliance',
            //     title: 'Compliance',
            //     translateKey: 'nav.groupMenu.collapse.item3',
            //     icon: '',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     authority: [],
            //     subMenu: [],
            // },
            {
                key: 'groupMenu.collapse.item7',
                path: '/company-admin',
                title: 'Company Group Admin',
                translateKey: 'nav.groupMenu.collapse.item7',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'groupMenu.collapse.item9',
                path: '/return-setup',
                title: 'Return Setup',
                translateKey: 'nav.groupMenu.collapse.item9',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
    },
  {
                key: 'groupMenu.collapse.item12',
                path: '/posh',
                title: 'POSH',
                translateKey: 'nav.groupMenu.collapse.item12',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
             {
                key: 'groupMenu.collapse.item15',
                path: '/auditSetup',
                title: 'Audit Setup',
                translateKey: 'nav.groupMenu.collapse.item15',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
//   {
//                 key: 'groupMenu.collapse.item14',
//                 path: '/register',
//                 title: 'Register',
//                 translateKey: 'nav.groupMenu.collapse.item14',
//                 icon: '',
//                 type: NAV_ITEM_TYPE_ITEM,
//                 authority: [],
//                 subMenu: [],
//             },
            // {
            //     key: 'groupMenu.collapse.item8',
            //     path: '/external-user',
            //     title: 'External User',
            //     translateKey: 'nav.groupMenu.collapse.item8',
            //     icon: '',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     authority: [],
            //     subMenu: [],
            // },
            // {
            //     key: 'groupMenu.collapse.item5',
            //     path: '/register-template',
            //     title: 'Register Template',
            //     translateKey: 'nav.groupMenu.collapse.item5',
            //     icon: '',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     authority: [],
            //     subMenu: [],
            // },
            // {
            //     key: 'groupMenu.collapse.item6',
            //     path: '/role',
            //     title: 'Role Configuration',
            //     translateKey: 'nav.groupMenu.collapse.item6',
            //     icon: '',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     authority: [],
            //     subMenu: [],
            // },
        ],
    },
]

export default navigationConfig
